if GetLocale() == "zhTW" then
qcLocalize = {
	ABYSSALDEPTHS = "地獄深淵",
	AHNKAHETTHEOLDKINGDOM = "安卡罕特:古王國", -- Needs review
	AHNQIRAJ = "安其拉", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "安其拉: 沒落的王朝",
	ALCHEMY = "煉金術", -- Needs review
	ALTERACVALLEY = "奧特蘭克山谷 \009", -- Needs review
	ARATHIBASIN = "阿拉希盆地", -- Needs review
	ARATHIHIGHLANDS = "阿拉希高地",
	ARCHAEOLOGY = "考古學", -- Needs review
	ASHENVALE = "梣谷",
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "奧奇奈地穴", -- Needs review
	AUCHINDOUN = "奧齊頓", -- Needs review
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "阿茲歐-奈幽", -- Needs review
	AZSHARA = "艾薩拉",
	AZUREMYSTISLE = "藍謎島",
	BADLANDS = "荒蕪之地",
	BARADINHOLD = "巴拉丁堡", -- Needs review
	BATTLEGROUNDS = "戰場", -- Needs review
	BATTLEPETS = "戰鬥寵物", -- Needs review
	BLACKFATHOMDEEPS = "黑澗深淵", -- Needs review
	BLACKROCKCAVERNS = "黑石洞穴", -- Needs review
	BLACKROCKDEPTHS = "黑石深淵", -- Needs review
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "黑石塔", -- Needs review
	BLACKSMITHING = "鍛造", -- Needs review
	BLACKTEMPLE = "黑暗神廟", -- Needs review
	BLACKWINGDESCENT = "黑翼陷窟", -- Needs review
	BLACKWINGLAIR = "黑翼之巢", -- Needs review
	BLADESEDGEMOUNTAINS = "劍刃山脈",
	BLASTEDLANDS = "詛咒之地",
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "血謎島",
	BOREANTUNDRA = "北風凍原",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "啤酒節", -- Needs review
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "燃燒平原",
	CAVERNSOFTIME = "時光之穴", -- Needs review
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "兒童週", -- Needs review
	CLASSES = "職業", -- Needs review
	CLASSQUESTS = "職業任務", -- Needs review
	CLEARUPDATECACHE = "清除更新快取", -- Needs review
	COILFANGRESERVOIR = "盤牙蓄湖", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "已合併的地圖與任務列表過濾器", -- Needs review
	CONFIGSUBTITLE = "這些選項允許你改變 Quest Completist 對其自身資料處理和過濾的方式", -- Needs review
	CONFIGTITLE = "Quest Completist - 設置", -- Needs review
	CONTINENTS = "地區", -- Needs review
	COOKING = "烹飪", -- Needs review
	CRYSTALSONGFOREST = "水晶之歌森林",
	DALARAN = "達拉然",
	DARKMOONFAIRE = "暗月馬戲團", -- Needs review
	DARKSHORE = "黑海岸",
	DARNASSUS = "達納蘇斯",
	DAYOFTHEDEAD = "亡者節", -- Needs review
	DEADWINDPASS = "逆風小徑",
	DEATHKNIGHT = "死亡騎士", -- Needs review
	DEEPHOLM = "地深之源",
	DEEPRUNTRAM = "礦道地鐵",
	DESOLACE = "淒涼之地",
	DIREMAUL = "厄運之槌", -- Needs review
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "龍骨荒野",
	DRAGONSOUL = "巨龍之魂", -- Needs review
	DRAKTHARONKEEP = "德拉克薩隆要塞", -- Needs review
	DREADWASTES = "悚然荒野",
	DRUID = "德魯伊", -- Needs review
	DUNGEONSANDRAIDS = "地下城與團隊", -- Needs review
	DUNMOROGH = "丹莫洛",
	DUROTAR = "杜洛塔",
	DUSKWOOD = "暮色森林",
	DUSTWALLOWMARSH = "塵泥沼澤",
	EASTERNKINGDOMS = "東都王國",
	EASTERNPLAGUELANDS = "東瘟疫之地",
	ELEMENTALBONDS = "元素桎梏", -- Needs review
	ELWYNNFOREST = "艾爾文森林",
	ENCHANTING = "附魔", -- Needs review
	ENDTIME = "終焉之刻", -- Needs review
	ENGINEERING = "工程學", -- Needs review
	EVERSONGWOODS = "永歌森林",
	EYEOFTHESTORM = "暴風之眼", -- Needs review
	FELWOOD = "費伍德森林",
	FERALAS = "菲拉斯",
	FIRELANDS = "火源之界", -- Needs review
	FIRELANDSINVASION = "火源之界進軍行動", -- Needs review
	FIRSTAID = "急救", -- Needs review
	FISHING = "釣魚", -- Needs review
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "鬼魂之地",
	GILNEAS = "吉爾尼斯", -- Needs review
	GILNEASCITY = "吉爾尼斯城", -- Needs review
	GNOMEREGAN = "諾姆瑞根", -- Needs review
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "格瑞姆巴托", -- Needs review
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "灰白之丘",
	GRUULSLAIR = "戈魯爾之巢", -- Needs review
	GUNDRAK = "剛德拉克", -- Needs review
	HALLOWSEND = "萬鬼節", -- Needs review
	HALLSOFLIGHTNING = "雷光大廳", -- Needs review
	HALLSOFORIGINATION = "起源大廳", -- Needs review
	HALLSOFREFLECTION = "倒影大廳", -- Needs review
	HALLSOFSTONE = "石之大廳", -- Needs review
	HARVESTFESTIVAL = "收穫節", -- Needs review
	HELLFIRECITADEL = "地獄火堡壘", -- Needs review
	HELLFIREPENINSULA = "地獄火半島",
	HELLFIRERAMPARTS = "地獄火壁壘", -- Needs review
	HERBALISM = "草藥學", -- Needs review
	HIDECOMPLETEDQUESTS = "隱藏已完成的任務", -- Needs review
	HIDEINPROGRESSQUESTS = "隱藏進行中的任務", -- Needs review
	HIDELOWLEVELQUESTS = "隱藏低等級的任務", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "隱藏尚未開始的季節性任務", -- Needs review
	HIDEOTHERFACTIONQUESTS = "隱藏其他陣營的任務", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "隱藏其他專業的任務", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "隱藏其他種族和職業任務", -- Needs review
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "希爾斯布萊德丘陵",
	HOUROFTWILIGHT = "暮光之時", -- Needs review
	HOWLINGFJORD = "凜風峽灣",
	HROTHGARSLANDING = "赫魯斯加臺地",
	HUNTER = "獵人", -- Needs review
	HYJALSUMMIT = "海加爾山之巔", -- Needs review
	ICECROWN = "寒冰皇冠",
	ICECROWNCITADEL = "冰冠城塞", -- Needs review
	INSCRIPTION = "銘文學", -- Needs review
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "鐵爐堡",
	ISLEOFCONQUEST = "征服之島", -- Needs review
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "奎爾達納斯之島",
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "珠寶設計", -- Needs review
	KALIMDOR = "卡林多",
	KARAZHAN = "卡拉贊", -- Needs review
	KELPTHARFOREST = "凱波薩爾森林",
	KEZAN = "凱贊",
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "喀撒朗蠻荒",
	KUNLAISUMMIT = "崑萊峰",
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "製皮", -- Needs review
	LEGENDARY = "傳奇", -- Needs review
	LOCHMODAN = "洛克莫丹",
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "托維爾的失落之城", -- Needs review
	LOVEISINTHEAIR = "愛就在身邊", -- Needs review
	LUNARFESTIVAL = "新年慶典", -- Needs review
	MAGE = "法師", -- Needs review
	MAGISTERSTERRACE = "博學者殿堂", -- Needs review
	MAGTHERIDONSLAIR = "瑪瑟里頓的巢穴", -- Needs review
	MANATOMBS = "法力之墓", -- Needs review
	MAPFILTERS = "地圖過濾器", -- Needs review
	MARAUDON = "瑪拉頓", -- Needs review
	MIDSUMMERFIREFESTIVAL = "仲夏火焰節", -- Needs review
	MINING = "採礦", -- Needs review
	MISCELLANEOUS = "雜項", -- Needs review
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "魔古山寶庫",
	MOLTENCORE = "熔火之心", -- Needs review
	MOLTENFRONT = "熔岩前線",
	MONK = "武僧", -- Needs review
	MOONGLADE = "月光林地",
	MOUNTHYJAL = "海加爾山",
	MULGORE = "莫高雷",
	NAGRAND = "納葛蘭",
	NAXXRAMAS = "納克薩瑪斯", -- Needs review
	NETHERSTORM = "虛空風暴",
	NEWYEARSEVE = "除夕夜", -- Needs review
	NOBLEGARDEN = "貴族花園", -- Needs review
	NORTHERNBARRENS = "北貧瘠之地",
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "北荊棘谷",
	NORTHREND = "北裂境",
	OLDHILLSBRADFOOTHILLS = "希爾斯布萊德丘陵舊址", -- Needs review
	ONYXIASLAIR = "奧妮克希亞的巢穴", -- Needs review
	OPTIONS = "選項", -- Needs review
	ORGRIMMAR = "奧格瑪",
	OUTLAND = "外域",
	PALACEOFTHEHEAVENS = "魔古山宮", -- Needs review
	PALADIN = "聖騎士", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "潘達利亞",
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "進行伺服器查詢中...", -- Needs review
	PILGRIMSBOUNTY = "旅人豐年祭", -- Needs review
	PITOFSARON = "薩倫之淵", -- Needs review
	PRIEST = "牧師", -- Needs review
	PROFESSIONS = "專業", -- Needs review
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "已經對伺服器進行查詢的要求...", -- Needs review
	QUESTLISTFILTERS = "任務列表過濾器", -- Needs review
	QUESTSFOUND = "已找到 %d 個任務", -- Needs review
	RAGEFIRECHASM = "怒焰裂谷", -- Needs review
	RAIDS = "團隊", -- Needs review
	RAZORFENDOWNS = "剃刀高地", -- Needs review
	RAZORFENKRAUL = "剃刀沼澤", -- Needs review
	REDRIDGEMOUNTAINS = "赤脊山",
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "盜賊", -- Needs review
	RUINSOFAHNQIRAJ = "安其拉廢墟", -- Needs review
	RUINSOFGILNEAS = "吉爾尼斯廢墟",
	RUINSOFGILNEASCITY = "吉爾尼斯城廢墟",
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "血色修道院", -- Needs review
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "通靈學院", -- Needs review
	SEARINGGORGE = "灼熱峽谷", -- Needs review
	SEASONAL = "季節性", -- Needs review
	SERPENTSHRINECAVERN = "毒蛇神殿洞穴", -- Needs review
	SETHEKKHALLS = "塞司克大廳", -- Needs review
	SHADOPANMONASTERY = "影潘僧院", -- Needs review
	SHADOWFANGKEEP = "影牙城堡", -- Needs review
	SHADOWLABYRINTH = "暗影迷宮", -- Needs review
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "影月谷", -- Needs review
	SHAMAN = "薩滿", -- Needs review
	SHATTRATHCITY = "撒塔斯城", -- Needs review
	SHIMMERINGEXPANSE = "閃光瀚洋", -- Needs review
	SHOLAZARBASIN = "休拉薩盆地", -- Needs review
	SHOWMAPICONS = "顯示地圖小圖示", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "怒兆寺圍城", -- Needs review
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "希利蘇斯",
	SILVERMOONCITY = "銀月城", -- Needs review
	SILVERPINEFOREST = "銀松森林", -- Needs review
	SILVERSHARDMINES = "碎銀礦坑", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "剝皮", -- Needs review
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "排序：以字母順序", -- Needs review
	SORTLEVEL = "排序：以等級", -- Needs review
	SOUTHERNBARRENS = "南貧瘠之地",
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "特殊", -- Needs review
	SPECIALS = "特殊", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "石爪山脈",
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "風暴烈酒酒坊", -- Needs review
	STORMWINDCITY = "暴風城", -- Needs review
	STRANDOFTHEANCIENTS = "遠祖灘頭", -- Needs review
	STRANGLETHORNVALE = "荊棘谷", -- Needs review
	STRATHOLME = "斯坦索姆", -- Needs review
	SUNKENTEMPLE = "沉沒的神廟", -- Needs review
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "太陽之井高地", -- Needs review
	SWAMPOFSORROWS = "悲傷沼澤", -- Needs review
	TAILORING = "裁縫", -- Needs review
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "塔納利斯",
	TELDRASSIL = "泰達希爾",
	TEMPESTKEEP = "風暴要塞", -- Needs review
	TEMPLEOFAHNQIRAJ = "安其拉神廟", -- Needs review
	TEMPLEOFKOTMOGU = "科特魔古神廟", -- Needs review
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "紅鶴寺", -- Needs review
	TEROKKARFOREST = "泰洛卡森林", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "亞克崔茲", -- Needs review
	THEBASTIONOFTWILIGHT = "暮光堡壘", -- Needs review
	THEBATTLEFORGILNEAS = "吉爾尼斯之戰", -- Needs review
	THEBLACKMORASS = "開啟黑暗之門", -- Needs review
	THEBLOODFURNACE = "血熔爐", -- Needs review
	THEBOTANICA = ":波塔尼卡", -- Needs review
	THECAPEOFSTRANGLETHORN = "荊棘谷海角", -- Needs review
	THECULLINGOFSTRATHOLME = "斯坦索姆的抉擇", -- Needs review
	THEDEADMINES = "死亡礦坑", -- Needs review
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "艾克索達",
	THEEYE = "風暴要塞", -- Needs review
	THEEYEOFETERNITY = "永恆之眼", -- Needs review
	THEFORGEOFSOULS = "眾魂熔爐", -- Needs review
	THEGATEOFTHESETTINGSUN = "日暮之門", -- Needs review
	THEHALFHILLMARKET = "半丘市集", -- Needs review
	THEHINTERLANDS = "辛特蘭", -- Needs review
	THEJADEFOREST = "翠玉林", -- Needs review
	THELOSTISLES = "失落群島", -- Needs review
	THEMAELSTROM = "大漩渦", -- Needs review
	THEMECHANAR = "麥克納爾", -- Needs review
	THENEXUS = "奧核之心", -- Needs review
	THEOBSIDIANSANCTUM = "黑曜聖所", -- Needs review
	THEOCULUS = "奧核之眼", -- Needs review
	THERUBYSANCTUM = "晶紅聖所", -- Needs review
	THESHATTEREDHALLS = "破碎大廳", -- Needs review
	THESLAVEPENS = "奴隸監獄", -- Needs review
	THESTEAMVAULT = "蒸汽洞窟", -- Needs review
	THESTOCKADE = "監獄", -- Needs review
	THESTONECORE = "石岩之心", -- Needs review
	THESTORMPEAKS = "風暴群山", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "玉蛟寺", -- Needs review
	THEUNDERBOG = "深幽泥沼", -- Needs review
	THEVEILEDSTAIR = "隱藏的階梯", -- Needs review
	THEVIOLETHOLD = "紫羅蘭堡", -- Needs review
	THEVORTEXPINNACLE = "漩渦尖塔", -- Needs review
	THEWANDERINGISLE = "漂流島", -- Needs review
	THEZANDALARI = "贊達拉", -- Needs review
	THOUSANDNEEDLES = "千針石林",
	THRONEOFTHEFOURWINDS = "四風王座", -- Needs review
	THRONEOFTHETIDES = "海潮王座", -- Needs review
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "雷霆崖",
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "提里斯法林地", -- Needs review
	TOLBARAD = "托巴拉德", -- Needs review
	TOLBARADPENINSULA = "托巴拉德半島", -- Needs review
	TOURNAMENT = "全球爭霸戰", -- Needs review
	TOWNLONGSTEPPES = "螳螂荒野", -- Needs review
	TRIALOFTHECHAMPION = "勇士試煉", -- Needs review
	TRIALOFTHECRUSADER = "十字軍試煉", -- Needs review
	TWILIGHTHIGHLANDS = "暮光高地", -- Needs review
	TWINPEAKS = "雙子峰", -- Needs review
	ULDAMAN = "奧達曼", -- Needs review
	ULDUAR = "奧杜亞", -- Needs review
	ULDUM = "奧丹姆",
	UNDERCITY = "幽暗城", -- Needs review
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "安戈洛環形山",
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "俄特加德要塞", -- Needs review
	UTGARDEPINNACLE = "俄特加德之巔", -- Needs review
	VALEOFETERNALBLOSSOMS = "恆春谷", -- Needs review
	VALLEYOFTHEFOURWINDS = "四風峽", -- Needs review
	VASHJIR = "瓦許伊爾", -- Needs review
	VAULTOFARCHAVON = "亞夏梵穹殿", -- Needs review
	WAILINGCAVERNS = "哀嚎洞穴", -- Needs review
	WARLOCK = "術士", -- Needs review
	WARRIOR = "戰士", -- Needs review
	WARSONGGULCH = "戰歌峽谷", -- Needs review
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "永恆之井", -- Needs review
	WESTERNPLAGUELANDS = "西瘟疫之地", -- Needs review
	WESTFALL = "西部荒野", -- Needs review
	WETLANDS = "濕地", -- Needs review
	WINTERGRASP = "冬握湖", -- Needs review
	WINTERSPRING = "冬泉谷",
	WINTERVEIL = "冬幕節", -- Needs review
	WORLDEVENTS = "世界事件", -- Needs review
	ZANGARMARSH = "贊格沼澤", -- Needs review
	ZULAMAN = "祖阿曼", -- Needs review
	ZULDRAK = "祖爾德拉克", -- Needs review
	ZULFARRAK = "祖爾法拉克", -- Needs review
	ZULGURUB = "祖爾格拉布", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET = "Darkheart Thicket",
	EYEOFAZSHARA = "Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
	KROKUUN = "Krokuun",
	ANTORANWASTES = "Antoran Wastes",
	ARGUS = "Argus",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Dreadscar Rift",
	ANTORUSTHEBURNINGTHRONE = "Antorus, the Burning Throne",
	HELHEIM = "Helheim",
	THESEATOFTHETRIUMVIRATE = "The Seat Of The Triumvirate",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	DRUSTVAR = "Drustvar",
	STORMSONGVALLEY = "Stormsong Valley",
	TIRAGARDESOUND = "Tiragarde Sound",
	NAZMIR = "Nazmir",
	VOLDUN = "Vol`dun",
	ZULDAZAR = "Zuldazar",
	ATALDAZAR = "Atal'Dazar",	 	
	CRUCIBLEOFSTORMS = "Crucible of Storms",	
	FREEHOLD = "Freehold",		
	KINGSREST = "Kings' Rest",
	SHRINEOFTHESTORM = "Shrine of the Storm",
	SIEGEOFBORAUS = "Siege Of Boralus",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	TEMPLEOFSETHRALISS = "Temple of Sethraliss",
	THRUNDERROT = "The Underrot",
	TOLDAGOR = "Tol Dagor",
	ULDIR = "Uldir",
	WAYCRESTMANOR = "Waycrest Manor",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
	THEMOTHERLOAD = "The Motherload!!",
	BATTLEOFDAZARALOR = "Battle of Dazar`alor",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	CHAMBEROFHEART = "Chamber Of Heart",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	MECHAGONISLAND = "Mechagon Island",
	NAZJATAR = "Nazjatar",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "Terrace Of Endless Spring",
	TEMP = "Temp",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
}

end