if GetLocale() == "itIT" then
qcLocalize = {
	ABYSSALDEPTHS = "Profondità Abissali", -- Needs review
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: The Old Kingdom", -- Requires localization
	AHNQIRAJ = "Ahn'Qiraj", -- Requires localization
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: Il Regno Perduto", -- Needs review
	ALCHEMY = "Alchimia", -- Needs review
	ALTERACVALLEY = "Valle d'Alterac", -- Needs review
	ARATHIBASIN = "Bacino d' Arathi", -- Needs review
	ARATHIHIGHLANDS = "Altopiani d'Arathi", -- Needs review
	ARCHAEOLOGY = "Archeologia", -- Needs review
	ASHENVALE = "Valtetra", -- Needs review
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "Auchenai Crypts", -- Requires localization
	AUCHINDOUN = "Auchindoun", -- Requires localization
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Requires localization
	AZSHARA = "Azshara", -- Needs review
	AZUREMYSTISLE = "Isola Brumazzurra", -- Needs review
	BADLANDS = "Maleterre", -- Needs review
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Campo di Battaglia", -- Needs review
	BATTLEPETS = "Battle Pets", -- Requires localization
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Forgiatura", -- Needs review
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "Montagne Spinaguzza", -- Needs review
	BLASTEDLANDS = "Terre Devastate", -- Needs review
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "Isola Brumacremisi", -- Needs review
	BOREANTUNDRA = "Tundra Boreale", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Brewfest", -- Requires localization
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "Steppe Ardenti", -- Needs review
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "Children's Week", -- Requires localization
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "Cooking", -- Requires localization
	CRYSTALSONGFOREST = "Foresta di Cristallo", -- Needs review
	DALARAN = "Dalaran", -- Needs review
	DARKMOONFAIRE = "Darkmoon Faire", -- Requires localization
	DARKSHORE = "Rivafosca", -- Needs review
	DARNASSUS = "Darnassus", -- Needs review
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEADWINDPASS = "Valico Ventomorto", -- Needs review
	DEATHKNIGHT = "Death Knight", -- Requires localization
	DEEPHOLM = "Rocciafonda", -- Needs review
	DEEPRUNTRAM = "Tram degli Abissi", -- Needs review
	DESOLACE = "Desolanda", -- Needs review
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "Dracombra", -- Needs review
	DRAGONSOUL = "Dragon Soul", -- Requires localization
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Distese del Terrore", -- Needs review
	DRUID = "Druid", -- Requires localization
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	DUNMOROGH = "Dun Morogh", -- Needs review
	DUROTAR = "Durotar", -- Needs review
	DUSKWOOD = "Boscovespro", -- Needs review
	DUSTWALLOWMARSH = "Acquemorte", -- Needs review
	EASTERNKINGDOMS = "Regni Orientali", -- Needs review
	EASTERNPLAGUELANDS = "Terre Infette Orientali", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "Foresta di Elwynn", -- Needs review
	ENCHANTING = "Enchanting", -- Requires localization
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "Engineering", -- Requires localization
	EVERSONGWOODS = "Boschi di Cantoeterno", -- Needs review
	EYEOFTHESTORM = "Eye of the Storm", -- Requires localization
	FELWOOD = "Vilbosco", -- Needs review
	FERALAS = "Feralas", -- Needs review
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "First Aid", -- Requires localization
	FISHING = "Fishing", -- Requires localization
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "Terre Spettrali", -- Needs review
	GILNEAS = "Gilneas", -- Requires localization
	GILNEASCITY = "Gilneas City", -- Requires localization
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "Colli Bradi", -- Needs review
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "Hallow's End", -- Requires localization
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "Harvest Festival", -- Requires localization
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "Penisola del Fuoco Infernale", -- Needs review
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "Herbalism", -- Requires localization
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "Alture di Colletorto", -- Needs review
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "Fiordo Echeggiante", -- Needs review
	HROTHGARSLANDING = "Hrothgar's Landing", -- Requires localization
	HUNTER = "Hunter", -- Requires localization
	HYJALSUMMIT = "Hyjal Summit", -- Requires localization
	ICECROWN = "Icecrown", -- Requires localization
	ICECROWNCITADEL = "Icecrown Citadel", -- Requires localization
	INSCRIPTION = "Inscription", -- Requires localization
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "Ironforge", -- Requires localization
	ISLEOFCONQUEST = "Isle of Conquest", -- Requires localization
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "Isle of Quel'Danas", -- Requires localization
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Jewelcrafting", -- Requires localization
	KALIMDOR = "Kalimdor", -- Needs review
	KARAZHAN = "Karazhan", -- Requires localization
	KELPTHARFOREST = "Kelp'thar Forest", -- Requires localization
	KEZAN = "Kezan", -- Requires localization
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "Krasarang Wilds", -- Requires localization
	KUNLAISUMMIT = "Kun-Lai Summit", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "Leatherworking", -- Requires localization
	LEGENDARY = "Legendary", -- Requires localization
	LOCHMODAN = "Loch Modan", -- Requires localization
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "Lost City of the Tol'vir", -- Requires localization
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "Lunar Festival", -- Requires localization
	MAGE = "Mage", -- Requires localization
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "Mana-Tombs", -- Requires localization
	MAPFILTERS = "Map Filters", -- Requires localization
	MARAUDON = "Maraudon", -- Requires localization
	MIDSUMMERFIREFESTIVAL = "Midsummer Fire Festival", -- Requires localization
	MINING = "Mining", -- Requires localization
	MISCELLANEOUS = "Varie", -- Needs review
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "Molten Front", -- Requires localization
	MONK = "Monk", -- Requires localization
	MOONGLADE = "Nottequieta", -- Needs review
	MOUNTHYJAL = "Monte Hyjal", -- Needs review
	MULGORE = "Mulgore", -- Needs review
	NAGRAND = "Nagrand", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "Landa Fatua", -- Needs review
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "Noblegarden", -- Requires localization
	NORTHERNBARRENS = "Savane Settentrionali", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "Rovotorto Settentrionale", -- Needs review
	NORTHREND = "Nordania", -- Needs review
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Options", -- Requires localization
	ORGRIMMAR = "Orgrimmar", -- Needs review
	OUTLAND = "Terre Esterne", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "Paladin", -- Requires localization
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "Pandaria", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Priest", -- Requires localization
	PROFESSIONS = "Professions", -- Requires localization
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "Un'interrogazione al server è stata richiesta", -- Needs review
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "Raids", -- Requires localization
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "Montagne Crestarossa", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "Rogue", -- Requires localization
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "Rovine di Gilneas", -- Needs review
	RUINSOFGILNEASCITY = "Rovine della città di Gilneas", -- Needs review
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Gorgia Rovente", -- Needs review
	SEASONAL = "Seasonal", -- Requires localization
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-Pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "Valle di Torvaluna", -- Needs review
	SHAMAN = "Shaman", -- Requires localization
	SHATTRATHCITY = "Shattrat", -- Needs review
	SHIMMERINGEXPANSE = "Distesa Scintillante", -- Needs review
	SHOLAZARBASIN = "Bacino di Sholazar", -- Needs review
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "Silitus", -- Needs review
	SILVERMOONCITY = "Lunargenta", -- Needs review
	SILVERPINEFOREST = "Selva Pinargento", -- Needs review
	SILVERSHARDMINES = "Silver Shard Mines", -- Requires localization
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Skinning", -- Requires localization
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNBARRENS = "Savane Meridionali", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "Special", -- Requires localization
	SPECIALS = "Specials", -- Requires localization
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "Vette di Petrartiglio", -- Needs review
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "Roccavento", -- Needs review
	STRANDOFTHEANCIENTS = "Strand of the Ancients", -- Requires localization
	STRANGLETHORNVALE = "Valle di Rovotorto", -- Needs review
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "Palude del Dolore", -- Needs review
	TAILORING = "Tailoring", -- Requires localization
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "Tanaris", -- Needs review
	TELDRASSIL = "Teldrassil", -- Needs review
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "Temple of Ahn'Qiraj", -- Requires localization
	TEMPLEOFKOTMOGU = "Temple of Kotmogu", -- Requires localization
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "Temple of the Red Crane", -- Requires localization
	TEROKKARFOREST = "Foresta di Terokk", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "The Battle for Gilneas", -- Requires localization
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "The Botanica", -- Requires localization
	THECAPEOFSTRANGLETHORN = "Capo di Rovotorto", -- Needs review
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "The Deadmines", -- Requires localization
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "Exodar", -- Needs review
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "The Eye of Eternity", -- Requires localization
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "Entroterre", -- Needs review
	THEJADEFOREST = "Foresta di Giada", -- Needs review
	THELOSTISLES = "Isole Perdute", -- Needs review
	THEMAELSTROM = "Maelstrom", -- Needs review
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "The Nexus", -- Requires localization
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "The Ruby Sanctum", -- Requires localization
	THESHATTEREDHALLS = "The Shattered Halls", -- Requires localization
	THESLAVEPENS = "The Slave Pens", -- Requires localization
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "The Stonecore", -- Requires localization
	THESTORMPEAKS = "Cime Tempestose", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "Isola Errante", -- Needs review
	THEZANDALARI = "The Zandalari", -- Requires localization
	THOUSANDNEEDLES = "Millepicchi", -- Needs review
	THRONEOFTHEFOURWINDS = "Throne of the Four Winds", -- Requires localization
	THRONEOFTHETIDES = "Throne of the Tides", -- Requires localization
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "Picco del Tuono", -- Needs review
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "Radure di Tirisfal", -- Needs review
	TOLBARAD = "Tol Barad", -- Needs review
	TOLBARADPENINSULA = "Penisola di Tol Barad", -- Needs review
	TOURNAMENT = "Tournament", -- Requires localization
	TOWNLONGSTEPPES = "Steppe di Tong Long", -- Needs review
	TRIALOFTHECHAMPION = "Trial of the Champion", -- Requires localization
	TRIALOFTHECRUSADER = "Trial of the Crusader", -- Requires localization
	TWILIGHTHIGHLANDS = "Alture del Crepuscolo", -- Needs review
	TWINPEAKS = "Twin Peaks", -- Requires localization
	ULDAMAN = "Uldaman", -- Requires localization
	ULDUAR = "Ulduar", -- Requires localization
	ULDUM = "Uldum", -- Needs review
	UNDERCITY = "Sepulcra", -- Needs review
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "Cratere di Un'Goro", -- Needs review
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "Vallata dell'Eterna Primavera", -- Needs review
	VALLEYOFTHEFOURWINDS = "Valle dei Quattro Venti", -- Needs review
	VASHJIR = "Vashj'ir", -- Needs review
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Caverna dei Lamenti", -- Needs review
	WARLOCK = "Warlock", -- Requires localization
	WARRIOR = "Warrior", -- Requires localization
	WARSONGGULCH = "Warsong Gulch", -- Requires localization
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "Terre Infette Occidentali", -- Needs review
	WESTFALL = "Marche Occidentali", -- Needs review
	WETLANDS = "Paludi Grigie", -- Needs review
	WINTERGRASP = "Lungoinverno", -- Needs review
	WINTERSPRING = "Fontefredda", -- Needs review
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	ZANGARMARSH = "Paludi di Zangar", -- Needs review
	ZULAMAN = "Zul'Aman", -- Requires localization
	ZULDRAK = "Zul'Drak", -- Needs review
	ZULFARRAK = "Zul'Farrak", -- Requires localization
	ZULGURUB = "Zul'Gurub", -- Requires localization
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET	 = "Darkheart Thicket",
	EYEOFAZSHARA = "	Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "	The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
	KROKUUN = "Krokuun",
	ANTORANWASTES = "Antoran Wastes",
	ARGUS = "Argus",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Dreadscar Rift",
	ANTORUSTHEBURNINGTHRONE = "Antorus, the Burning Throne",
	HELHEIM = "Helheim",
	THESEATOFTHETRIUMVIRATE = "The Seat Of The Triumvirate",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	DRUSTVAR = "Drustvar",
	STORMSONGVALLEY = "Stormsong Valley",
	TIRAGARDESOUND = "Tiragarde Sound",
	NAZMIR = "Nazmir",
	VOLDUN = "Vol`dun",
	ZULDAZAR = "Zuldazar",
	ATALDAZAR = "Atal'Dazar",	 	
	CRUCIBLEOFSTORMS = "Crucible of Storms",	
	FREEHOLD = "Freehold",		
	KINGSREST = "Kings' Rest",
	SHRINEOFTHESTORM = "Shrine of the Storm",
	SIEGEOFBORAUS = "Siege Of Boralus",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	TEMPLEOFSETHRALISS = "Temple of Sethraliss",
	THRUNDERROT = "The Underrot",
	TOLDAGOR = "Tol Dagor",
	ULDIR = "Uldir",
	WAYCRESTMANOR = "Waycrest Manor",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
	THEMOTHERLOAD = "The Motherload!!",
	BATTLEOFDAZARALOR = "Battle of Dazar`alor",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	CHAMBEROFHEART = "Chamber Of Heart",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	MECHAGONISLAND = "Mechagon Island",
	NAZJATAR = "Nazjatar",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "Terrace Of Endless Spring",
	TEMP = "Temp",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
}

end