if GetLocale() == "zhCN" then
qcLocalize = {
	ABYSSALDEPTHS = "Abyssal Depths", -- Requires localization
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: The Old Kingdom", -- Requires localization
	AHNQIRAJ = "安其拉", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "安其拉：失落的帝国", -- Needs review
	ALCHEMY = "炼金术", -- Needs review
	ALTERACVALLEY = "Alterac Valley", -- Requires localization
	ARATHIBASIN = "Arathi Basin", -- Requires localization
	ARATHIHIGHLANDS = "阿拉希高地", -- Needs review
	ARCHAEOLOGY = "Archaeology", -- Requires localization
	ASHENVALE = "灰谷", -- Needs review
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "Auchenai Crypts", -- Requires localization
	AUCHINDOUN = "Auchindoun", -- Requires localization
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Requires localization
	AZSHARA = "艾萨拉", -- Needs review
	AZUREMYSTISLE = "秘蓝岛", -- Needs review
	BADLANDS = "荒芜之地", -- Needs review
	BARADINHOLD = "Baradin Hold", -- Requires localization
	BATTLEGROUNDS = "Battlegrounds", -- Requires localization
	BATTLEPETS = "战斗宠物", -- Needs review
	BLACKFATHOMDEEPS = "Blackfathom Deeps", -- Requires localization
	BLACKROCKCAVERNS = "Blackrock Caverns", -- Requires localization
	BLACKROCKDEPTHS = "Blackrock Depths", -- Requires localization
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "Blackrock Spire", -- Requires localization
	BLACKSMITHING = "Blacksmithing", -- Requires localization
	BLACKTEMPLE = "Black Temple", -- Requires localization
	BLACKWINGDESCENT = "Blackwing Descent", -- Requires localization
	BLACKWINGLAIR = "Blackwing Lair", -- Requires localization
	BLADESEDGEMOUNTAINS = "刀锋山", -- Needs review
	BLASTEDLANDS = "风暴之地", -- Needs review
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "秘血岛", -- Needs review
	BOREANTUNDRA = "北风苔原", -- Needs review
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Brewfest", -- Requires localization
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "Burning Steppes", -- Requires localization
	CAVERNSOFTIME = "Caverns of Time", -- Requires localization
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "Children's Week", -- Requires localization
	CLASSES = "Classes", -- Requires localization
	CLASSQUESTS = "Class Quests", -- Requires localization
	CLEARUPDATECACHE = "Clear Update Cache...", -- Requires localization
	COILFANGRESERVOIR = "Coilfang Reservoir", -- Requires localization
	COMBINEDMAPANDQUESTFILTERS = "Combined Map & Quest List Filters", -- Requires localization
	CONFIGSUBTITLE = "These options allow you to change the way that Quest Completist handles and filters its data.", -- Requires localization
	CONFIGTITLE = "Quest Completist - Configuration", -- Requires localization
	CONTINENTS = "Continents", -- Requires localization
	COOKING = "Cooking", -- Requires localization
	CRYSTALSONGFOREST = "晶歌森林", -- Needs review
	DALARAN = "达拉然", -- Needs review
	DARKMOONFAIRE = "Darkmoon Faire", -- Requires localization
	DARKSHORE = "黑海岸", -- Needs review
	DARNASSUS = "达拉苏斯", -- Needs review
	DAYOFTHEDEAD = "Day of the Dead", -- Requires localization
	DEADWINDPASS = "逆风小径", -- Needs review
	DEATHKNIGHT = "Death Knight", -- Requires localization
	DEEPHOLM = "深岩之洲", -- Needs review
	DEEPRUNTRAM = "Deeprun Tram", -- Requires localization
	DESOLACE = "凄凉之地", -- Needs review
	DIREMAUL = "Dire Maul", -- Requires localization
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "龙骨荒野", -- Needs review
	DRAGONSOUL = "巨龙之魂", -- Needs review
	DRAKTHARONKEEP = "Drak'Tharon Keep", -- Requires localization
	DREADWASTES = "Dread Wastes", -- Requires localization
	DRUID = "Druid", -- Requires localization
	DUNGEONSANDRAIDS = "Dungeons & Raids", -- Requires localization
	DUNMOROGH = "丹莫罗", -- Needs review
	DUROTAR = "杜隆塔尔", -- Needs review
	DUSKWOOD = "Duskwood", -- Requires localization
	DUSTWALLOWMARSH = "尘泥沼泽", -- Needs review
	EASTERNKINGDOMS = "东部王国", -- Needs review
	EASTERNPLAGUELANDS = "东瘟疫之地", -- Needs review
	ELEMENTALBONDS = "Elemental Bonds", -- Requires localization
	ELWYNNFOREST = "艾尔文森林", -- Needs review
	ENCHANTING = "附魔", -- Needs review
	ENDTIME = "End Time", -- Requires localization
	ENGINEERING = "工程学", -- Needs review
	EVERSONGWOODS = "永歌森林", -- Needs review
	EYEOFTHESTORM = "风暴之眼", -- Needs review
	FELWOOD = "费伍德森林", -- Needs review
	FERALAS = "菲拉斯", -- Needs review
	FIRELANDS = "Firelands", -- Requires localization
	FIRELANDSINVASION = "Firelands Invasion", -- Requires localization
	FIRSTAID = "急救", -- Needs review
	FISHING = "钓鱼", -- Needs review
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "幽魂之地", -- Needs review
	GILNEAS = "吉尔尼斯", -- Needs review
	GILNEASCITY = "吉尔尼斯城", -- Needs review
	GNOMEREGAN = "Gnomeregan", -- Requires localization
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Requires localization
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "Grizzly Hills", -- Requires localization
	GRUULSLAIR = "Gruul's Lair", -- Requires localization
	GUNDRAK = "Gundrak", -- Requires localization
	HALLOWSEND = "万圣节", -- Needs review
	HALLSOFLIGHTNING = "Halls of Lightning", -- Requires localization
	HALLSOFORIGINATION = "Halls of Origination", -- Requires localization
	HALLSOFREFLECTION = "Halls of Reflection", -- Requires localization
	HALLSOFSTONE = "Halls of Stone", -- Requires localization
	HARVESTFESTIVAL = "收获节", -- Needs review
	HELLFIRECITADEL = "Hellfire Citadel", -- Requires localization
	HELLFIREPENINSULA = "地狱火半岛", -- Needs review
	HELLFIRERAMPARTS = "Hellfire Ramparts", -- Requires localization
	HERBALISM = "草药学", -- Needs review
	HIDECOMPLETEDQUESTS = "Hide Completed Quests", -- Requires localization
	HIDEINPROGRESSQUESTS = "Hide In-Progress Quests", -- Requires localization
	HIDELOWLEVELQUESTS = "Hide Low Level Quests", -- Requires localization
	HIDENONACTIVESEASONALQUESTS = "Hide Non-Active Seasonal Quests", -- Requires localization
	HIDEOTHERFACTIONQUESTS = "Hide Other Faction Quests", -- Requires localization
	HIDEOTHERPROFESSIONQUESTS = "Hide Other Profession Quests", -- Requires localization
	HIDEOTHERRACEANDCLASSQUESTS = "Hide Other Race & Class Quests", -- Requires localization
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "希尔斯布莱德丘陵", -- Needs review
	HOUROFTWILIGHT = "Hour of Twilight", -- Requires localization
	HOWLINGFJORD = "嚎风峡湾", -- Needs review
	HROTHGARSLANDING = "Hrothgar's Landing", -- Requires localization
	HUNTER = "Hunter", -- Requires localization
	HYJALSUMMIT = "海加尔之巅", -- Needs review
	ICECROWN = "冰冠冰川", -- Needs review
	ICECROWNCITADEL = "冰冠城塞", -- Needs review
	INSCRIPTION = "Inscription", -- Requires localization
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "铁炉堡", -- Needs review
	ISLEOFCONQUEST = "Isle of Conquest", -- Requires localization
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "奎尔丹纳斯岛", -- Needs review
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "珠宝加工", -- Needs review
	KALIMDOR = "卡利姆多", -- Needs review
	KARAZHAN = "卡拉赞", -- Needs review
	KELPTHARFOREST = "Kelp'thar Forest", -- Requires localization
	KEZAN = "科赞", -- Needs review
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "Krasarang Wilds", -- Requires localization
	KUNLAISUMMIT = "Kun-Lai Summit", -- Requires localization
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "制皮", -- Needs review
	LEGENDARY = "Legendary", -- Requires localization
	LOCHMODAN = "洛克莫丹", -- Needs review
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "托维尔失落之城", -- Needs review
	LOVEISINTHEAIR = "Love is in the Air", -- Requires localization
	LUNARFESTIVAL = "春节", -- Needs review
	MAGE = "法师", -- Needs review
	MAGISTERSTERRACE = "Magisters' Terrace", -- Requires localization
	MAGTHERIDONSLAIR = "Magtheridon's Lair", -- Requires localization
	MANATOMBS = "法力陵墓", -- Needs review
	MAPFILTERS = "Map Filters", -- Requires localization
	MARAUDON = "玛拉顿的巢穴", -- Needs review
	MIDSUMMERFIREFESTIVAL = "仲夏节", -- Needs review
	MINING = "采矿", -- Needs review
	MISCELLANEOUS = "Miscellaneous", -- Requires localization
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "Mogu'shan Vaults", -- Requires localization
	MOLTENCORE = "Molten Core", -- Requires localization
	MOLTENFRONT = "熔火前线", -- Needs review
	MONK = "武僧", -- Needs review
	MOONGLADE = "月光林地", -- Needs review
	MOUNTHYJAL = "海加尔山", -- Needs review
	MULGORE = "莫高雷", -- Needs review
	NAGRAND = "纳格兰", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Requires localization
	NETHERSTORM = "虚空风暴", -- Needs review
	NEWYEARSEVE = "New Year's Eve", -- Requires localization
	NOBLEGARDEN = "Noblegarden", -- Requires localization
	NORTHERNBARRENS = "北贫瘠之地", -- Needs review
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "北荆棘谷", -- Needs review
	NORTHREND = "诺森德", -- Needs review
	OLDHILLSBRADFOOTHILLS = "Old Hillsbrad Foothills", -- Requires localization
	ONYXIASLAIR = "Onyxia's Lair", -- Requires localization
	OPTIONS = "Options", -- Requires localization
	ORGRIMMAR = "奥格瑞玛", -- Needs review
	OUTLAND = "外域", -- Needs review
	PALACEOFTHEHEAVENS = "Palace of the Heavens", -- Requires localization
	PALADIN = "圣骑士", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "潘达利亚", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Perform Server Query...", -- Requires localization
	PILGRIMSBOUNTY = "Pilgrim's Bounty", -- Requires localization
	PITOFSARON = "Pit of Saron", -- Requires localization
	PRIEST = "Priest", -- Requires localization
	PROFESSIONS = "Professions", -- Requires localization
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "A server query has been requested...", -- Requires localization
	QUESTLISTFILTERS = "Quest List Filters", -- Requires localization
	QUESTSFOUND = "%d Quests Found", -- Requires localization
	RAGEFIRECHASM = "Ragefire Chasm", -- Requires localization
	RAIDS = "团队", -- Needs review
	RAZORFENDOWNS = "Razorfen Downs", -- Requires localization
	RAZORFENKRAUL = "Razorfen Kraul", -- Requires localization
	REDRIDGEMOUNTAINS = "赤脊山", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "潜行者", -- Needs review
	RUINSOFAHNQIRAJ = "Ruins of Ahn'Qiraj", -- Requires localization
	RUINSOFGILNEAS = "吉尔尼斯废墟", -- Needs review
	RUINSOFGILNEASCITY = "吉尔尼斯城废墟", -- Needs review
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "Scarlet Monastery", -- Requires localization
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Requires localization
	SEARINGGORGE = "Searing Gorge", -- Requires localization
	SEASONAL = "节日", -- Needs review
	SERPENTSHRINECAVERN = "Serpentshrine Cavern", -- Requires localization
	SETHEKKHALLS = "Sethekk Halls", -- Requires localization
	SHADOPANMONASTERY = "Shado-Pan Monastery", -- Requires localization
	SHADOWFANGKEEP = "Shadowfang Keep", -- Requires localization
	SHADOWLABYRINTH = "Shadow Labyrinth", -- Requires localization
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "影月谷", -- Needs review
	SHAMAN = "萨满祭司", -- Needs review
	SHATTRATHCITY = "沙塔斯城", -- Needs review
	SHIMMERINGEXPANSE = "Shimmering Expanse", -- Requires localization
	SHOLAZARBASIN = "索拉查盆地", -- Needs review
	SHOWMAPICONS = "Show Map Icons", -- Requires localization
	SIEGEOFNIUZAOTEMPLE = "Siege of Niuzao Temple", -- Requires localization
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "希利苏斯", -- Needs review
	SILVERMOONCITY = "银月城", -- Needs review
	SILVERPINEFOREST = "银松森林", -- Needs review
	SILVERSHARDMINES = "Silver Shard Mines", -- Requires localization
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Skinning", -- Requires localization
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "Sort: Alphabetically", -- Requires localization
	SORTLEVEL = "Sort: Level", -- Requires localization
	SOUTHERNBARRENS = "南贫瘠之地", -- Needs review
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "特殊", -- Needs review
	SPECIALS = "特殊", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "石爪山脉", -- Needs review
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "Stormstout Brewery", -- Requires localization
	STORMWINDCITY = "暴风城", -- Needs review
	STRANDOFTHEANCIENTS = "Strand of the Ancients", -- Requires localization
	STRANGLETHORNVALE = "Stranglethorn Vale", -- Requires localization
	STRATHOLME = "Stratholme", -- Requires localization
	SUNKENTEMPLE = "Sunken Temple", -- Requires localization
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "Sunwell Plateau", -- Requires localization
	SWAMPOFSORROWS = "悲伤沼泽", -- Needs review
	TAILORING = "裁缝", -- Needs review
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "塔纳利斯", -- Needs review
	TELDRASSIL = "泰达希尔", -- Needs review
	TEMPESTKEEP = "Tempest Keep", -- Requires localization
	TEMPLEOFAHNQIRAJ = "安琪拉神庙", -- Needs review
	TEMPLEOFKOTMOGU = "Temple of Kotmogu", -- Requires localization
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "红玉圣殿", -- Needs review
	TEROKKARFOREST = "泰罗卡森林", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "The Arcatraz", -- Requires localization
	THEBASTIONOFTWILIGHT = "The Bastion of Twilight", -- Requires localization
	THEBATTLEFORGILNEAS = "吉尔尼斯之战", -- Needs review
	THEBLACKMORASS = "The Black Morass", -- Requires localization
	THEBLOODFURNACE = "The Blood Furnace", -- Requires localization
	THEBOTANICA = "生态船", -- Needs review
	THECAPEOFSTRANGLETHORN = "The Cape of Stranglethorn", -- Requires localization
	THECULLINGOFSTRATHOLME = "The Culling of Stratholme", -- Requires localization
	THEDEADMINES = "死亡矿井", -- Needs review
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "埃索达", -- Needs review
	THEEYE = "The Eye", -- Requires localization
	THEEYEOFETERNITY = "永恒之眼", -- Needs review
	THEFORGEOFSOULS = "The Forge of Souls", -- Requires localization
	THEGATEOFTHESETTINGSUN = "The Gate of the Setting Sun", -- Requires localization
	THEHALFHILLMARKET = "The Halfhill Market", -- Requires localization
	THEHINTERLANDS = "The Hinterlands", -- Requires localization
	THEJADEFOREST = "翡翠森林", -- Needs review
	THELOSTISLES = "迷踪岛", -- Needs review
	THEMAELSTROM = "The Maelstrom", -- Requires localization
	THEMECHANAR = "The Mechanar", -- Requires localization
	THENEXUS = "纳克萨玛斯", -- Needs review
	THEOBSIDIANSANCTUM = "The Obsidian Sanctum", -- Requires localization
	THEOCULUS = "The Oculus", -- Requires localization
	THERUBYSANCTUM = "红玉龙圣殿", -- Needs review
	THESHATTEREDHALLS = "破碎大厅", -- Needs review
	THESLAVEPENS = "奴隶围栏", -- Needs review
	THESTEAMVAULT = "The Steamvault", -- Requires localization
	THESTOCKADE = "The Stockade", -- Requires localization
	THESTONECORE = "巨石之核", -- Needs review
	THESTORMPEAKS = "风暴峭壁", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "The Temple of the Jade Serpent", -- Requires localization
	THEUNDERBOG = "The Underbog", -- Requires localization
	THEVEILEDSTAIR = "The Veiled Stair", -- Requires localization
	THEVIOLETHOLD = "The Violet Hold", -- Requires localization
	THEVORTEXPINNACLE = "The Vortex Pinnacle", -- Requires localization
	THEWANDERINGISLE = "The Wandering Isle", -- Requires localization
	THEZANDALARI = "The Zandalari", -- Requires localization
	THOUSANDNEEDLES = "千针石林", -- Needs review
	THRONEOFTHEFOURWINDS = "四风王座", -- Needs review
	THRONEOFTHETIDES = "潮汐王座", -- Needs review
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "雷霆崖", -- Needs review
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "提瑞斯法林地", -- Needs review
	TOLBARAD = "托尔巴拉德", -- Needs review
	TOLBARADPENINSULA = "托尔巴拉德半岛", -- Needs review
	TOURNAMENT = "Tournament", -- Requires localization
	TOWNLONGSTEPPES = "Townlong Steppes", -- Requires localization
	TRIALOFTHECHAMPION = "冠军的试炼", -- Needs review
	TRIALOFTHECRUSADER = "十字军的试炼", -- Needs review
	TWILIGHTHIGHLANDS = "Twilight Highlands", -- Requires localization
	TWINPEAKS = "双子峰", -- Needs review
	ULDAMAN = "奥达曼", -- Needs review
	ULDUAR = "奥杜尔", -- Needs review
	ULDUM = "奥丹姆", -- Needs review
	UNDERCITY = "幽暗城", -- Needs review
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "安戈洛环形山", -- Needs review
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "Utgarde Keep", -- Requires localization
	UTGARDEPINNACLE = "Utgarde Pinnacle", -- Requires localization
	VALEOFETERNALBLOSSOMS = "Vale of Eternal Blossoms", -- Requires localization
	VALLEYOFTHEFOURWINDS = "Valley of the Four Winds", -- Requires localization
	VASHJIR = "瓦丝琪尔", -- Needs review
	VAULTOFARCHAVON = "Vault of Archavon", -- Requires localization
	WAILINGCAVERNS = "Wailing Caverns", -- Requires localization
	WARLOCK = "Warlock", -- Requires localization
	WARRIOR = "Warrior", -- Requires localization
	WARSONGGULCH = "Warsong Gulch", -- Requires localization
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "Well of Eternity", -- Requires localization
	WESTERNPLAGUELANDS = "西瘟疫之地", -- Needs review
	WESTFALL = "Westfall", -- Requires localization
	WETLANDS = "湿地", -- Needs review
	WINTERGRASP = "冬握湖", -- Needs review
	WINTERSPRING = "冬泉谷", -- Needs review
	WINTERVEIL = "Winter Veil", -- Requires localization
	WORLDEVENTS = "World Events", -- Requires localization
	ZANGARMARSH = "Zangarmarsh", -- Requires localization
	ZULAMAN = "祖阿曼", -- Needs review
	ZULDRAK = "祖达克", -- Needs review
	ZULFARRAK = "祖尔法拉克", -- Needs review
	ZULGURUB = "祖尔格拉布", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET = "Darkheart Thicket",
	EYEOFAZSHARA = "Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
	KROKUUN = "Krokuun",
	ANTORANWASTES = "Antoran Wastes",
	ARGUS = "Argus",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Dreadscar Rift",
	ANTORUSTHEBURNINGTHRONE = "Antorus, the Burning Throne",
	HELHEIM = "Helheim",
	THESEATOFTHETRIUMVIRATE = "The Seat Of The Triumvirate",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	DRUSTVAR = "Drustvar",
	STORMSONGVALLEY = "Stormsong Valley",
	TIRAGARDESOUND = "Tiragarde Sound",
	NAZMIR = "Nazmir",
	VOLDUN = "Vol`dun",
	ZULDAZAR = "Zuldazar",
	ATALDAZAR = "Atal'Dazar",	 	
	CRUCIBLEOFSTORMS = "Crucible of Storms",	
	FREEHOLD = "Freehold",		
	KINGSREST = "Kings' Rest",
	SHRINEOFTHESTORM = "Shrine of the Storm",
	SIEGEOFBORAUS = "Siege Of Boralus",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	TEMPLEOFSETHRALISS = "Temple of Sethraliss",
	THRUNDERROT = "The Underrot",
	TOLDAGOR = "Tol Dagor",
	ULDIR = "Uldir",
	WAYCRESTMANOR = "Waycrest Manor",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
	THEMOTHERLOAD = "The Motherload!!",
	BATTLEOFDAZARALOR = "Battle of Dazar`alor",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	CHAMBEROFHEART = "Chamber Of Heart",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	MECHAGONISLAND = "Mechagon Island",
	NAZJATAR = "Nazjatar",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "Terrace Of Endless Spring",
	TEMP = "Temp",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
}

end