if GetLocale() == "esMX" then
qcLocalize = {
	ABYSSALDEPTHS = "Profundidades Abisales",
	AHNKAHETTHEOLDKINGDOM = "Ahn'kahet: El Antiguo Reino", -- Needs review
	AHNQIRAJ = "Ahn'Qiraj", -- Needs review
	AHNQIRAJTHEFALLENKINGDOM = "Ahn'Qiraj: El Reino Caído",
	ALCHEMY = "Alquimia", -- Needs review
	ALTERACVALLEY = "Valle de Alterac", -- Needs review
	ARATHIBASIN = "Cuenca de Arathi", -- Needs review
	ARATHIHIGHLANDS = "Tierras Altas de Arathi",
	ARCHAEOLOGY = "Arqueología", -- Needs review
	ASHENVALE = "Vallefresno",
	ASHRAN = "Ashran", -- Requires localization
	ASSAULTONTHEDARKPORTAL = "Assault on the Dark Portal", -- Requires localization
	AUCHENAICRYPTS = "Criptas Auchenai", -- Needs review
	AUCHINDOUN = "Auchindoun", -- Needs review
	AZEROTH = "Azeroth", -- Requires localization
	AZJOLNERUB = "Azjol-Nerub", -- Needs review
	AZSHARA = "Azshara",
	AZUREMYSTISLE = "Isla Bruma Azur",
	BADLANDS = "Tierras Inhóspitas",
	BARADINHOLD = "Bastión de Baradin", -- Needs review
	BATTLEGROUNDS = "Los Campos de Batalla", -- Needs review
	BATTLEPETS = "Mascotas de Duelo", -- Needs review
	BLACKFATHOMDEEPS = "Cavernas de Brazanegra", -- Needs review
	BLACKROCKCAVERNS = "Cavernas Roca Negra", -- Needs review
	BLACKROCKDEPTHS = "Profundidades de Roca Negra", -- Needs review
	BLACKROCKFOUNDRY = "Blackrock Foundry", -- Requires localization
	BLACKROCKSPIRE = "Cumbre de Roca Negra", -- Needs review
	BLACKSMITHING = "Herrería", -- Needs review
	BLACKTEMPLE = "Templo Oscuro", -- Needs review
	BLACKWINGDESCENT = "Descenso de Alanegra", -- Needs review
	BLACKWINGLAIR = "Guarida de Alanegra", -- Needs review
	BLADESEDGEMOUNTAINS = "Montañas Filospada",
	BLASTEDLANDS = "Las Tierras Devastadas",
	BLOODMAULSLAGMINES = "Bloodmaul Slag Mines", -- Requires localization
	BLOODMYSTISLE = "Isla Bruma de Sangre",
	BOREANTUNDRA = "Tundra Boreal",
	BRAWLERSGUILD = "Brawler's Guild", -- Requires localization
	BREWFEST = "Fiesta de la Cerveza", -- Needs review
	BREWMOONFESTIVAL = "Brewmoon Festival", -- Requires localization
	BURNINGSTEPPES = "Las Estepas Ardientes",
	CAVERNSOFTIME = "Cavernas del Tiempo", -- Needs review
	CENTRALKALIMDOR = "Central Kalimdor", -- Requires localization
	CHILDRENSWEEK = "La Semana de los Niños", -- Needs review
	CLASSES = "Clases", -- Needs review
	CLASSQUESTS = "Misiones de clase", -- Needs review
	CLEARUPDATECACHE = "Limpiar la data del caché", -- Needs review
	COILFANGRESERVOIR = "Reserva Colmillo Torcido", -- Needs review
	COMBINEDMAPANDQUESTFILTERS = "Filtros combinados de mapas y listas de misiones", -- Needs review
	CONFIGSUBTITLE = "Estas opciones te permiten cambiar la manera en que Quest Completlist maneja y filtra la información", -- Needs review
	CONFIGTITLE = "Quest Completlist - Configuración", -- Needs review
	CONTINENTS = "Continentes", -- Needs review
	COOKING = "Cocina", -- Needs review
	CRYSTALSONGFOREST = "Bosque Canto de Cristal",
	DALARAN = "Dalaran",
	DARKMOONFAIRE = "Feria de la Luna Negra", -- Needs review
	DARKSHORE = "Costa Oscura",
	DARNASSUS = "Darnassus",
	DAYOFTHEDEAD = "Festividad de los muertos ", -- Needs review
	DEADWINDPASS = "Paso de la Muerte",
	DEATHKNIGHT = "Caballero de la Muerte", -- Needs review
	DEEPHOLM = "Infralar",
	DEEPRUNTRAM = "Tren Subterráneo", -- Needs review
	DESOLACE = "Desolace",
	DIREMAUL = "La Masacre", -- Needs review
	DRAENOR = "Draenor", -- Requires localization
	DRAGONBLIGHT = "Cementerio de Dragones", -- Needs review
	DRAGONSOUL = "Alma de Dragón", -- Needs review
	DRAKTHARONKEEP = "Fortaleza de Drak'Tharon", -- Needs review
	DREADWASTES = "Desierto del Pavor",
	DRUID = "Druida", -- Needs review
	DUNGEONSANDRAIDS = "Calabozos y bandas", -- Needs review
	DUNMOROGH = "Dun Morogh",
	DUROTAR = "Durotar",
	DUSKWOOD = "Bosque del Ocaso",
	DUSTWALLOWMARSH = "Marjal Revolcafango",
	EASTERNKINGDOMS = "Reinos del Este",
	EASTERNPLAGUELANDS = "Tierras de la Peste del Este",
	ELEMENTALBONDS = "Vínclos elementales", -- Needs review
	ELWYNNFOREST = "Bosque de Elwynn",
	ENCHANTING = "Encantamiento", -- Needs review
	ENDTIME = "Fin de los Días", -- Needs review
	ENGINEERING = "Ingenieria", -- Needs review
	EVERSONGWOODS = "Bosque Canción Eterna",
	EYEOFTHESTORM = "Ojo de la Tormenta", -- Needs review
	FELWOOD = "Frondavil",
	FERALAS = "Feralas",
	FIRELANDS = "Tierras de Fuego", -- Needs review
	FIRELANDSINVASION = "Invasión de las Tierras de Fuego", -- Needs review
	FIRSTAID = "Primeros auxilios", -- Needs review
	FISHING = "Pesca", -- Needs review
	FROSTFIRERIDGE = "Frostfire Ridge", -- Requires localization
	GARRISONCAMPAIGN = "Garrison Campaign", -- Requires localization
	GARRISONSUPPORT = "Garrison Support", -- Requires localization
	GATEOFTHESETTINGSUN = "Gate of the Setting Sun", -- Requires localization
	GHOSTLANDS = "Tierras Fantasma",
	GILNEAS = "Gilneas", -- Needs review
	GILNEASCITY = "Ciudad de Gilneas", -- Needs review
	GNOMEREGAN = "Gnomeregan", -- Needs review
	GORGROND = "Gorgrond", -- Requires localization
	GREENSTONEVILLAGE = "Greenstone Village", -- Requires localization
	GRIMBATOL = "Grim Batol", -- Needs review
	GRIMRAILDEPOT = "Grimrail Depot", -- Requires localization
	GRIZZLYHILLS = "Colinas Pardas",
	GRUULSLAIR = "Guarida de Gruul", -- Needs review
	GUNDRAK = "Gundrak", -- Needs review
	HALLOWSEND = "Halloween", -- Needs review
	HALLSOFLIGHTNING = "Cámaras de Relámpagos", -- Needs review
	HALLSOFORIGINATION = "Cámaras de los Orígenes", -- Needs review
	HALLSOFREFLECTION = "Cámaras de Reflexión", -- Needs review
	HALLSOFSTONE = "Cámaras de Piedra", -- Needs review
	HARVESTFESTIVAL = "Festival de la Cosecha", -- Needs review
	HELLFIRECITADEL = "Ciudadela de Fuego Infernal", -- Needs review
	HELLFIREPENINSULA = "Península del Fuego Infernal",
	HELLFIRERAMPARTS = "Murallas de Fuego Infernal", -- Needs review
	HERBALISM = "Recolectar hierbas", -- Needs review
	HIDECOMPLETEDQUESTS = "Esconder misiones completadas", -- Needs review
	HIDEINPROGRESSQUESTS = "Esconder misiones en progreso", -- Needs review
	HIDELOWLEVELQUESTS = "Esconder misiones de bajo nivel", -- Needs review
	HIDENONACTIVESEASONALQUESTS = "Esconder misiones inactivas de festividades", -- Needs review
	HIDEOTHERFACTIONQUESTS = "Esconder misiones de otras facciones", -- Needs review
	HIDEOTHERPROFESSIONQUESTS = "Esconder misiones de otras profesiones", -- Needs review
	HIDEOTHERRACEANDCLASSQUESTS = "Esconder misiones de otras razas y clases", -- Needs review
	HIGHMAUL = "Highmaul", -- Requires localization
	HILLSBRADFOOTHILLS = "Laderas de Trabalomas",
	HOUROFTWILIGHT = "Hora del Crepúsculo", -- Needs review
	HOWLINGFJORD = "Fiordo Aquilonal",
	HROTHGARSLANDING = "Desembarco de Hrothgar",
	HUNTER = "Cazador", -- Needs review
	HYJALSUMMIT = "La Cima Hyjal", -- Needs review
	ICECROWN = "Corona de Hielo", -- Needs review
	ICECROWNCITADEL = [=[Ciudadela de la Corona de Hielo
]=], -- Needs review
	INSCRIPTION = "Inscripción", -- Needs review
	IRONDOCKS = "Iron Docks", -- Requires localization
	IRONFORGE = "Forjaz", -- Needs review
	ISLEOFCONQUEST = "Isla de la Conquista", -- Needs review
	ISLEOFGIANTS = "Isle of Giants", -- Requires localization
	ISLEOFQUELDANAS = "Isla de Quel'Danas", -- Needs review
	ISLEOFTHUNDER = "Isle of Thunder", -- Requires localization
	JADETEMPLEGROUNDS = "Jade Temple Grounds", -- Requires localization
	JEWELCRAFTING = "Joyería", -- Needs review
	KALIMDOR = "Kalimdor",
	KARAZHAN = "Karazhan", -- Needs review
	KELPTHARFOREST = "Bosque Kelp'Thar", -- Needs review
	KEZAN = "Kezan", -- Needs review
	KHAZMODAN = "Khaz Modan", -- Requires localization
	KRASARANGWILDS = "Espesura Krasarang", -- Needs review
	KUNLAISUMMIT = "Cima Kun-Lai", -- Needs review
	LANDFALL = "Landfall", -- Requires localization
	LEATHERWORKING = "Peletería", -- Needs review
	LEGENDARY = "Legendario", -- Needs review
	LOCHMODAN = "Loch Modan", -- Needs review
	LORDAERON = "Lordaeron", -- Requires localization
	LOSTCITYOFTHETOLVIR = "Ciudad Perdida de los Tol'vir", -- Needs review
	LOVEISINTHEAIR = "Amor en el Aire", -- Needs review
	LUNARFESTIVAL = "Festival Lunar", -- Needs review
	MAGE = "Mago", -- Needs review
	MAGISTERSTERRACE = "Bancal del Magister", -- Needs review
	MAGTHERIDONSLAIR = "Guarida de Magtheridon", -- Needs review
	MANATOMBS = "Tumbas de Maná", -- Needs review
	MAPFILTERS = "Filtros de mapas", -- Needs review
	MARAUDON = "Maraudon", -- Needs review
	MIDSUMMERFIREFESTIVAL = "Festival de Fuego del Solsticio de Verano", -- Needs review
	MINING = "Minería", -- Needs review
	MISCELLANEOUS = "Miscelaneo", -- Needs review
	MOGUSHANPALACE = "Mogu'shan Palace", -- Requires localization
	MOGUSHANVAULTS = "Cámaras Mogu'shan", -- Needs review
	MOLTENCORE = "Núcleo de Magma", -- Needs review
	MOLTENFRONT = "Frente de Magma", -- Needs review
	MONK = "Monje", -- Needs review
	MOONGLADE = "Claro de la Luna",
	MOUNTHYJAL = "Monte Hyjal",
	MULGORE = "Mulgore",
	NAGRAND = "Nagrand", -- Needs review
	NAXXRAMAS = "Naxxramas", -- Needs review
	NETHERSTORM = "Tormenta Abisal", -- Needs review
	NEWYEARSEVE = "Víspera de Año Nuevo", -- Needs review
	NOBLEGARDEN = "Jardín Noble", -- Needs review
	NORTHERNBARRENS = "Los Baldíos del Norte",
	NORTHERNKALIMDOR = "Northern Kalimdor", -- Requires localization
	NORTHERNSTRANGLETHORN = "Norte de la Vega de Tuercespina", -- Needs review
	NORTHREND = "Rasganorte", -- Needs review
	OLDHILLSBRADFOOTHILLS = "Antiguas Laderas de Trabalomas", -- Needs review
	ONYXIASLAIR = "Guarida de Onyxia", -- Needs review
	OPTIONS = "Opciones", -- Needs review
	ORGRIMMAR = "Orgrimmar",
	OUTLAND = "Terrallende", -- Needs review
	PALACEOFTHEHEAVENS = "Palacio de los Cielos", -- Needs review
	PALADIN = "Paladín", -- Needs review
	PANDARENBREWMASTERS = "Pandaren Brewmasters", -- Requires localization
	PANDARENCAMPAIGN = "Pandaren Campaign", -- Requires localization
	PANDARIA = "Pandaria", -- Needs review
	PEAKOFSERENITY = "Peak of Serenity", -- Requires localization
	PERFORMSERVERQUERY = "Hacer una búsqueda en el servidor", -- Needs review
	PILGRIMSBOUNTY = "Generosidad del Peregrino", -- Needs review
	PITOFSARON = "Foso de Saron", -- Needs review
	PRIEST = "Sacerdote", -- Needs review
	PROFESSIONS = "Profesiones", -- Needs review
	PROVINGGROUNDS = "Proving Grounds", -- Requires localization
	QUERYREQUESTED = "Se ha solicitado una búsqueda en el servidor...", -- Needs review
	QUESTLISTFILTERS = "Filtros de lista de misiones", -- Needs review
	QUESTSFOUND = "Misión encontrada", -- Needs review
	RAGEFIRECHASM = "Sima Ígnea", -- Needs review
	RAIDS = "Bandas", -- Needs review
	RAZORFENDOWNS = "Zahúrda Rajacieno", -- Needs review
	RAZORFENKRAUL = "Horado Rajacieno", -- Needs review
	REDRIDGEMOUNTAINS = "Montañas Crestagrana", -- Needs review
	REGIONS = "Regions", -- Requires localization
	RIDING = "Riding", -- Requires localization
	ROGUE = "Pícaro", -- Needs review
	RUINSOFAHNQIRAJ = "Ruinas de Ahn'Qiraj", -- Needs review
	RUINSOFGILNEAS = "Ruinas de Gilneas", -- Needs review
	RUINSOFGILNEASCITY = "Ruinas de la Ciudad de Gilneas", -- Needs review
	SCARLETHALLS = "Scarlet Halls", -- Requires localization
	SCARLETMONASTERY = "Monasterio Escarlata", -- Needs review
	SCENARIO = "Scenario", -- Requires localization
	SCHOLOMANCE = "Scholomance", -- Needs review
	SEARINGGORGE = "La Garganta del Fuego", -- Needs review
	SEASONAL = "Estacional", -- Needs review
	SERPENTSHRINECAVERN = "Caverna Santuario Serpiente", -- Needs review
	SETHEKKHALLS = "Salas Sethekk", -- Needs review
	SHADOPANMONASTERY = "Monasterio del Shadopan", -- Needs review
	SHADOWFANGKEEP = "Castillo de Colmillo Oscuro", -- Needs review
	SHADOWLABYRINTH = "Laberinto de las Sombras", -- Needs review
	SHADOWMOONBURIALGROUNDS = "Shadowmoon Burial Grounds", -- Requires localization
	SHADOWMOONVALLEY = "Valle Sombraluna", -- Needs review
	SHAMAN = "Chamán", -- Needs review
	SHATTRATHCITY = "Ciudad de Shattrath", -- Needs review
	SHIMMERINGEXPANSE = "Extensión Bruñida", -- Needs review
	SHOLAZARBASIN = "Cuenca de Sholazar", -- Needs review
	SHOWMAPICONS = "Mostrar iconos en el mapa", -- Needs review
	SIEGEOFNIUZAOTEMPLE = "Asedio del Templo de Niuzao", -- Needs review
	SIEGEOFORGRIMMAR = "Siege of Orgrimmar", -- Requires localization
	SILITHUS = "Silithus",
	SILVERMOONCITY = "Ciudad de Lunargenta", -- Needs review
	SILVERPINEFOREST = "Bosque de Argénteos", -- Needs review
	SILVERSHARDMINES = "Minas Lonjaplata", -- Needs review
	SKETTIS = "Skettis", -- Requires localization
	SKINNING = "Desuello", -- Needs review
	SKYREACH = "Skyreach", -- Requires localization
	SORTALPHA = "Ordenar: Alfabéticamente", -- Needs review
	SORTLEVEL = "Ordenar: Por nivel", -- Needs review
	SOUTHERNBARRENS = "Los Baldíos del Sur",
	SOUTHERNKALIMDOR = "Southern Kalimdor", -- Requires localization
	SPECIAL = "Especial", -- Needs review
	SPECIALS = "Especiales", -- Needs review
	SPIREOFLIGHT = "Spire of Light", -- Requires localization
	SPIRESOFARAK = "Spires Of Arak", -- Requires localization
	STONETALONMOUNTAINS = "Sierra Espolón",
	STORMSHIELD = "Stormshield", -- Requires localization
	STORMSHIELDSTRONGHOLD = "Stormshield Stronghold", -- Requires localization
	STORMSTOUTBREWERY = "Cervecería del Trueno", -- Needs review
	STORMWINDCITY = "Ciudad de Ventormenta", -- Needs review
	STRANDOFTHEANCIENTS = "Playa de los Ancestros", -- Needs review
	STRANGLETHORNVALE = "Vega de Tuercespina", -- Needs review
	STRATHOLME = "Stratholme", -- Needs review
	SUNKENTEMPLE = "Templo Sumergido", -- Needs review
	SUNSTRIDERISLE = "Sunstrider Isle", -- Requires localization
	SUNWELLPLATEAU = "Meseta de La Fuente del Sol", -- Needs review
	SWAMPOFSORROWS = "Pantano de las Penas", -- Needs review
	TAILORING = "Sastrería", -- Needs review
	TALADOR = "Talador", -- Requires localization
	TANAANJUNGLE = "Tanaan Jungle", -- Requires localization
	TANARIS = "Tanaris",
	TELDRASSIL = "Teldrassil",
	TEMPESTKEEP = "El Castillo de la Tempestad", -- Needs review
	TEMPLEOFAHNQIRAJ = "Templo de Ahn'Qiraj", -- Needs review
	TEMPLEOFKOTMOGU = "Templo de Kotmogu", -- Needs review
	TEMPLEOFTHEJADESERPENT = "Temple of the Jade Serpent", -- Requires localization
	TEMPLEOFTHEREDCRANE = "Templo de la Grulla Roja", -- Needs review
	TEROKKARFOREST = "Bosque de Terokkar", -- Needs review
	THEARBORETUM = "The Arboretum", -- Requires localization
	THEARCATRAZ = "El Arcatraz", -- Needs review
	THEBASTIONOFTWILIGHT = "El Bastión del Crepúsculo", -- Needs review
	THEBATTLEFORGILNEAS = "La batalla de Glineas", -- Needs review
	THEBLACKMORASS = "La Ciénaga Negra", -- Needs review
	THEBLOODFURNACE = "El Horno de Sangre", -- Needs review
	THEBOTANICA = "El Invernáculo", -- Needs review
	THECAPEOFSTRANGLETHORN = "El Cabo de Tuercespina", -- Needs review
	THECULLINGOFSTRATHOLME = "La Matanza de Stratholme", -- Needs review
	THEDEADMINES = "Las Minas de la Muerte", -- Needs review
	THEEVERBLOOM = "The Everbloom", -- Requires localization
	THEEXODAR = "El Exodar",
	THEEYE = "El Castillo de la Tempestad", -- Needs review
	THEEYEOFETERNITY = "El Ojo de la Eternidad", -- Needs review
	THEFORGEOFSOULS = "The Forge of Souls", -- Needs review
	THEGATEOFTHESETTINGSUN = "Puerta del Sol Poniente", -- Needs review
	THEHALFHILLMARKET = "El Mercado del Alcor", -- Needs review
	THEHINTERLANDS = "Tierras del Interior", -- Needs review
	THEJADEFOREST = "El Bosque de Jade", -- Needs review
	THELOSTISLES = "Las Islas Perdidas", -- Needs review
	THEMAELSTROM = "La Vorágine", -- Needs review
	THEMECHANAR = "El Mechanar", -- Needs review
	THENEXUS = "El Nexo", -- Needs review
	THEOBSIDIANSANCTUM = "El Santuario Obsidiana", -- Needs review
	THEOCULUS = "El Oculus", -- Needs review
	THERUBYSANCTUM = "El Santuario Rubí", -- Needs review
	THESHATTEREDHALLS = "Las Salas Arrasadas", -- Needs review
	THESLAVEPENS = "Recinto de los Esclavos", -- Needs review
	THESTEAMVAULT = "La Cámara de Vapor", -- Needs review
	THESTOCKADE = "Las Mazmorras", -- Needs review
	THESTONECORE = "El Núcleo Pétreo", -- Needs review
	THESTORMPEAKS = "Las Cumbres Tormentosas", -- Needs review
	THETEMPLEOFTHEJADESERPENT = "El Templo de la Serpiente de Jade", -- Needs review
	THEUNDERBOG = "La Sotiénaga", -- Needs review
	THEVEILEDSTAIR = "La Escalera Velada", -- Needs review
	THEVIOLETHOLD = "El Bastión Violeta", -- Needs review
	THEVORTEXPINNACLE = "La Cumbre del Vórtice", -- Needs review
	THEWANDERINGISLE = "La Isla Errante", -- Needs review
	THEZANDALARI = "Los Zandalari", -- Needs review
	THOUSANDNEEDLES = "Las Mil Agujas",
	THRONEOFTHEFOURWINDS = "Trono de los Cuatro Vientos", -- Needs review
	THRONEOFTHETIDES = "Trono de las Mareas", -- Needs review
	THRONEOFTHUNDER = "Throne of Thunder", -- Requires localization
	THUNDERBLUFF = "Cima del Trueno",
	TIMELESSISLE = "Timeless Isle", -- Requires localization
	TIRISFALGLADES = "Claros de Tirisfal", -- Needs review
	TOLBARAD = "Tol Barad", -- Needs review
	TOLBARADPENINSULA = "Península de Tol Barad", -- Needs review
	TOURNAMENT = "Torneo", -- Needs review
	TOWNLONGSTEPPES = "Estepas de Tong Long", -- Needs review
	TRIALOFTHECHAMPION = "Prueba del Campeón", -- Needs review
	TRIALOFTHECRUSADER = "Prueba del Cruzado", -- Needs review
	TWILIGHTHIGHLANDS = "tierras Altas Crepusculares", -- Needs review
	TWINPEAKS = "Cumbres Gemelas", -- Needs review
	ULDAMAN = "Uldaman", -- Needs review
	ULDUAR = "Ulduar", -- Needs review
	ULDUM = "Uldum",
	UNDERCITY = "Entrañas", -- Needs review
	UNGAINGOO = "Unga Ingoo", -- Requires localization
	UNGOROCRATER = "Cráter de Un'Goro",
	UPPERBLACKROCKSPIRE = "Upper Blackrock Spire", -- Requires localization
	UTGARDEKEEP = "Fortaleza de Utgarde", -- Needs review
	UTGARDEPINNACLE = "Pináculo de Utgarde", -- Needs review
	VALEOFETERNALBLOSSOMS = "Valle de la Flor Eterna", -- Needs review
	VALLEYOFTHEFOURWINDS = "Valle de los Cuatro Vientos", -- Needs review
	VASHJIR = "Vashj'ir", -- Needs review
	VAULTOFARCHAVON = "Cámara de Archavon", -- Needs review
	WAILINGCAVERNS = "Cuevas de los Lamentos", -- Needs review
	WARLOCK = "Brujo", -- Needs review
	WARRIOR = "Guerrero", -- Needs review
	WARSONGGULCH = "Garganta Grito de Guerra", -- Needs review
	WARSPEAR = "Warspear", -- Requires localization
	WARSPEAROUTPOST = "Warspear Outpost", -- Requires localization
	WELLOFETERNITY = "Pozo de a Eternidad", -- Needs review
	WESTERNPLAGUELANDS = "Tierras de la Peste del Oeste", -- Needs review
	WESTFALL = "Páramos de Poniente", -- Needs review
	WETLANDS = "Los Humedales", -- Needs review
	WINTERGRASP = "Conquista del Invierno", -- Needs review
	WINTERSPRING = "Cuna del Invierno",
	WINTERVEIL = "El festín del Festival de Invierno", -- Needs review
	WORLDEVENTS = "Eventos del Mundo", -- Needs review
	ZANGARMARSH = "Marisma de Zangar", -- Needs review
	ZULAMAN = "Zul'Aman", -- Needs review
	ZULDRAK = "Zul'Drak", -- Needs review
	ZULFARRAK = "Zul'Farrak", -- Needs review
	ZULGURUB = "Zul'Gurub", -- Needs review
	THEBROKENISLES = "The Broken Isles",
	THEDREAMGROVE = "The Dreamgrove",
	AZSUNA = "Azsuna",
	HIGHMOUNTAIN = "Highmountain",
	STORMHEIM = "Stormheim",
	SURAMAR = "Suramar",
	VALSHARAH = "Val'sharah",
	DEMONHUNTER = "Demon Hunter",
	CONTESTCOMMING = "Contest comming shows wrong zone",
	HALLOFTHEGUARDIAN = "Hall of the Guardian",
	MARDUMTHESHATTEREDABYSS = "Mardum, the Shattered Abyss",
	NETHERLIGHTTEMPLE = "Netherlight Temple",
	SKYHOLD = "Skyhold",
	THEHEARTOFAZERTH = "The Heart of Azeroth",
	THEWANDERINGISLE = "The Wandering Isle Monk",
	TRUESHOTLODGE = "Trueshot Lodge Hunter",
	ACHERUSTHEEBONHOLD = "Acherus: The Ebon Hold",
	BLACKOOKHOLD = "Black Rook Hold",
	COURTOFSTARS = "Court of Stars",
	DARKHEARTTHICKET	 = "Darkheart Thicket",
	EYEOFAZSHARA = "	Eye of Azshara",
	HALLSOFVALOR = "Halls of Valor",
	MAWOFSOULS = "Maw of Souls",
	NELTHARIONSLAIR = "Neltharion's Lair",
	THEARCWAY = "The Arcway", 
	VAULTOFTHEWARDENS = "Vault of the Wardens",
	VIOLETHOLD = "Violet Hold",
	THEEMERALDNIGHTMARE = "The Emerald Nightmare",
	TRIALOFVALOR = "Trial of Valor",
	THENIGHTHOLD = "	The Nighthold",
	BROKENSHORE = "Broken Shore",
	LEGIONUNCATEQUEST = "Legion Uncategorized Quests",
	CATHEDRALOFETERNALNIGHT = "Cathedral of Eternal Night", 
	RETURNTOKARAZHAN = "Return to Karazhan",
 	TOMBOFSARGERAS = "Tomb of Sargeras",
	KROKUUN = "Krokuun",
	ANTORANWASTES = "Antoran Wastes",
	ARGUS = "Argus",
	MACAREE = "Mac'Aree",
	DREADSCARRIFT = "Dreadscar Rift",
	ANTORUSTHEBURNINGTHRONE = "Antorus, the Burning Throne",
	HELHEIM = "Helheim",
	THESEATOFTHETRIUMVIRATE = "The Seat Of The Triumvirate",
	EMERALDDREAMWAY = "Emerald Dreamway",
	BFA = "Battle For Azeroth",
	BFAUNCATEQUEST = "BFA Uncategorized Quests",
	ZANDALAR = "Zandalar",
	KULTIRAS = "Kul Tiras",
	THUNDERTOTEM = "Thunder Totem",
	DRUSTVAR = "Drustvar",
	STORMSONGVALLEY = "Stormsong Valley",
	TIRAGARDESOUND = "Tiragarde Sound",
	NAZMIR = "Nazmir",
	VOLDUN = "Vol`dun",
	ZULDAZAR = "Zuldazar",
	ATALDAZAR = "Atal'Dazar",	 	
	CRUCIBLEOFSTORMS = "Crucible of Storms",	
	FREEHOLD = "Freehold",		
	KINGSREST = "Kings' Rest",
	SHRINEOFTHESTORM = "Shrine of the Storm",
	SIEGEOFBORAUS = "Siege Of Boralus",
	SIEGEOFZULDAZAR = "Siege of Zuldazar",	
	TEMPLEOFSETHRALISS = "Temple of Sethraliss",
	THRUNDERROT = "The Underrot",
	TOLDAGOR = "Tol Dagor",
	ULDIR = "Uldir",
	WAYCRESTMANOR = "Waycrest Manor",
	THEDEATHOFCHROMIE = "The Deaths Of Chromie",
	THEMOTHERLOAD = "The Motherload!!",
	BATTLEOFDAZARALOR = "Battle of Dazar`alor",
    ALLIANCEWARCAMPAIGN = "Alliance War Campaign",
	HORDEWARCAMPAIGN = "Horde War Campaign",
	CHAMBEROFHEART = "Chamber Of Heart",
	THEDRAGONSSPINE = "The Dragon`s Spine",
	MECHAGONISLAND = "Mechagon Island",
	NAZJATAR = "Nazjatar",
	WARFRONTCONTRIBUTION = "Warfront Contribution",
	ISLANDEXPEDITIONS = "Island Expeditions",
	CLASSCAMPAINS = "Class Campains",
	TERRACEOFENLESSSPRINGS = "Terrace Of Endless Spring",
	TEMP = "Temp",
	PLAYERVSPLAYER = "Player Vs Player",
	HERITAGE = "Heritage",
	RATEDPVP = "Rated Pvp",
}

end